name: CD
on:
  release:
    types: [published]
  push:
  pull_request:
    branches: [ main, dev ]
    types: [ opened, edited ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:      
      COGNITO_USER_POOL_ID: "us-west-2_iq4sQovhE"

    steps:
    - uses: actions/checkout@v1 
    - name: debug1
      run: |
        echo "${{github.event_name}}"
    - name: DEV VARS
      if: (github.event_name == 'pull_request' || github.event_name == 'push' ) && github.ref == "refs/heads/dev"
      shell: bash
      run: |
        echo "ENVIRONMENT=dev" >> $GITHUB_ENV
        echo "BRANCH_NAME=$(echo ${GITHUB_HEAD_REF} | tr / -)" >> $GITHUB_ENV

    - name: STAGING VARS
      if: github.event_name == 'pull_request' || github.event_name == 'push'  && github.ref == "refs/heads/main"
      shell: bash
      run: |
        echo "ENVIRONMENT=staging" >> $GITHUB_ENV
        echo "BRANCH_NAME=$(echo ${GITHUB_HEAD_REF} | tr / -)" >> $GITHUB_ENV
    - name: PRODUCTION VARS
      if: github.event_name == 'release' 
      shell: bash
      run: |
        echo "ENVIRONMENT=production" >> $GITHUB_ENV
        echo "BRANCH_NAME=$(echo ${GITHUB_HEAD_REF} | tr / -)" >> $GITHUB_ENV
        
    - name: Debug
      run: 
        echo ${{ env.BRANCH_NAME }}
        echo ${{ env.ENVIRONMENT }}
 
