name: CD
on:
  release:
    types: [published]
  push:
    branches: [ main, dev ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:      
      COGNITO_USER_POOL_ID: "us-west-2_iq4sQovhE"

    steps:
    - uses: actions/checkout@v1 
    - name: debug1
      run: |
        echo "${{github.event_name}}"
    - name: DEV VARS
      if: ( github.event_name == 'push' ) && github.ref == 'refs/heads/dev'
      shell: bash
      run: |
        echo "ENVIRONMENT=dev" >> $GITHUB_ENV
        echo "BRANCH_NAME=$(echo ${GITHUB_HEAD_REF} | tr / -)" >> $GITHUB_ENV
    
    - name: TEST VARS
      if: ( github.event_name == 'push' ) && github.ref == 'refs/heads/test'
      shell: bash
      run: |
        echo "ENVIRONMENT=test" >> $GITHUB_ENV
        echo "BRANCH_NAME=$(echo ${GITHUB_HEAD_REF} | tr / -)" >> $GITHUB_ENV

    - name: STAGING VARS
      if: ( github.event_name == 'push') && github.ref == 'refs/heads/main'
      shell: bash
      run: |
        echo "ENVIRONMENT=staging" >> $GITHUB_ENV
        echo "BRANCH_NAME=$(echo ${GITHUB_HEAD_REF} | tr / -)" >> $GITHUB_ENV

    - name: PRODUCTION VARS
      if: github.event_name == 'release' 
      shell: bash
      run: |
        echo "ENVIRONMENT=production" >> $GITHUB_ENV
        echo "BRANCH_NAME=$(echo ${GITHUB_HEAD_REF} | tr / -)" >> $GITHUB_ENV
        
    - name: Debug
      run: 
        echo ${{ env.BRANCH_NAME }}
        echo ${{ env.ENVIRONMENT }}
 
    - name: Notify Slackers
      if: ${{env.GITHUB_ENV}} != null
      uses: rtCamp/action-slack-notify@v2.1.3
      env:
        # #tech-riot
        SLACK_WEBHOOK: https://hooks.slack.com/services/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
        SLACK_COLOR: ${{ job.status }}
        SLACK_ICON: https://files.slack.com/files-pri/T7MMVLUE6-F02HM1HUA30/screen_shot_2021-10-13_at_3.03.18_pm.png
        SLACK_TITLE: "branch  = ${{env.BRANCH_NAME}}"