name: CD
on:
  release:
    types: [published]
  push:
    branches: [ main, dev ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:      
      COGNITO_USER_POOL_ID: "us-west-2_iq4sQovhE"

    steps:
    - uses: actions/checkout@v1 
    - name: Deploy to ENV
      run: |
        ENVIRONMENT="dev"        
        if ["${{github.ref}}" = "refs/heads/main"]; then
          echo "switch to staging here..."
          ENVIRONMENT="staging"
        fi            
        if ["${{github.event.release}}"]; then
          ENVIRONMENT="production"
          echo "${{github.event.release}}"
        fi       
        echo "${{github.ref}} = github ref"
        echo "The env is $ENVIRONMENT"
