name: CD
on:
  release:
    types: [published]
  push:
    branches: [ main, dev ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:      
      COGNITO_USER_POOL_ID: "us-west-2_iq4sQovhE"

    steps:
    - uses: actions/checkout@v1 
    - name: debug1
      run: |
        echo "${{github.event_name}}"
    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch

    - name: set env.ENVIRONMENT
      shell: bash
      env: 
        BRANCH: "${{ steps.extract_branch.outputs.branch }}"
      run: |
        [[ "$BRANCH" == "dev" ]] &&  echo "ENVIRONMENT=dev" >> $GITHUB_ENV
        [[ "$BRANCH" == "test" ]] &&  echo "ENVIRONMENT=test" >> $GITHUB_ENV
        [[ "$BRANCH" == "main" ]] &&  echo "ENVIRONMENT=staging" >> $GITHUB_ENV
        echo "BRANCH=$BRANCH" >> $GITHUB_ENV
    
    - name: PRODUCTION VARS
      if: github.event_name == 'release' 
      shell: bash
      run: |
        echo "ENVIRONMENT=production" >> $GITHUB_ENV

        
    - name: Debug
      run: 
        echo ${{ env.BRANCH }}
        echo ${{ env.ENVIRONMENT }}
        
    - name: Notify Slackers
      if: ${{env.GITHUB_ENV}} != dev
      uses: act10ns/slack@v1.2.2
      env:
        SLACK_WEBHOOK_URL: https://hooks.slack.com/services/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
      with:
        # Specify success, failure, cancelled or a custom status.
        status: success
        # Report on the status of individual steps
#         steps: # optional
        # Override default channel with different channel or username
#         channel: # optional
#       uses: rtCamp/action-slack-notify@v2.1.3
#       env:
#         # #tech-riot
#         SLACK_WEBHOOK: https://hooks.slack.com/services/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
#         SLACK_COLOR: ${{ job.status }}
# #         SLACK_ICON: https://files.slack.com/files-pri/T7MMVLUE6-F02HM1HUA30/screen_shot_2021-10-13_at_3.03.18_pm.png
#         SLACK_TITLE: "branch  = ${{env.BRANCH}}"
