name: CD
on:
  release:
    types: [published]
  push:
    branches: [ main, dev ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:      
      COGNITO_USER_POOL_ID: "us-west-2_iq4sQovhE"

    steps:
    - uses: actions/checkout@v1    
    - name: Say Deploy to staging
      run: |
        echo "Deploy staging!!" 
        if ["${{github.ref}}" == "refs/heads/main"]
          echo "This is staging environment"
        fi       
        if ["${{github.ref}}" == "refs/heads/dev"]
          echo "This is dev environment"
        fi       
        if ["${{github.event.release}}"]
          echo "This is a release"
          echo "${{github.event.release}}"
        fi       
