name: CD
on:
  release:
    types: [published]
  push:
    branches: [ main, dev ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:      
      COGNITO_USER_POOL_ID: "us-west-2_iq4sQovhE"

    steps:
    - uses: actions/checkout@v1 
    - name: debug1
      run: |
        echo "${{github.event_name}}"
    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch

    - name: set env.ENVIRONMENT
      shell: bash
      env: 
        BRANCH: "${{ steps.extract_branch.outputs.branch }}"
      run: |
        [[ "$BRANCH" == "dev" ]] &&  echo "ENVIRONMENT=dev" >> $GITHUB_ENV
        [[ "$BRANCH" == "test" ]] &&  echo "ENVIRONMENT=test" >> $GITHUB_ENV
        [[ "$BRANCH" == "main" ]] &&  echo "ENVIRONMENT=staging" >> $GITHUB_ENV
        echo "BRANCH=$BRANCH" >> $GITHUB_ENV
    
    - name: PRODUCTION VARS
      if: github.event_name == 'release' 
      shell: bash
      run: |
        echo "ENVIRONMENT=production" >> $GITHUB_ENV

        
    - name: Debug
      run: 
        echo ${{ env.BRANCH }}
        echo ${{ env.ENVIRONMENT }}
        
    - name: Send GitHub Action trigger data to Slack workflow
      id: slack
      uses: slackapi/slack-github-action@v1.14.0
      env:
        SLACK_WEBHOOK_URL: ${{secrets.SLACK_WEBHOOK}}
